# Generated by Django 4.1.5 on 2023-03-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Preço"
                    ),
                ),
                ("codigo", models.IntegerField(verbose_name="Código")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        help_text="Selecione a Marca",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.marca",
                    ),
                ),
            ],
        ),
    ]
