# Generated by Django 4.1.5 on 2023-03-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55)),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valorRecebido",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Valor Recebido"
                    ),
                ),
                (
                    "valorParcela",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Valor da Parcela"
                    ),
                ),
                (
                    "dataVencimento",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Data de Vencimento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciclo", models.IntegerField(verbose_name="Ciclo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "produtos",
                    models.ForeignKey(
                        help_text="Selecione um Produto",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.produto",
                    ),
                ),
            ],
        ),
    ]
