# Generated by Django 4.1.5 on 2023-04-04 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_cliente_pagamento_pedido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamento",
            old_name="valorParcela",
            new_name="valor_parcela",
        ),
        migrations.RenameField(
            model_name="pagamento",
            old_name="valorRecebido",
            new_name="valor_recebido",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="dataVencimento",
        ),
        migrations.AddField(
            model_name="pagamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="data_vencimento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="forma_pagamento",
            field=models.CharField(
                default="", max_length=55, verbose_name="Forma pagamento"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="parcelas",
            field=models.IntegerField(default=1, verbose_name="Parcelas"),
            preserve_default=False,
        ),
    ]
