# Generated by Django 4.1.5 on 2023-05-23 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_rename_valorparcela_pagamento_valor_parcela_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                help_text="Selecione um Cliente",
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.cliente",
            ),
            preserve_default=False,
        ),
    ]
