# Generated by Django 4.1.5 on 2023-05-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_pedido_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                help_text="Selecione um Cliente",
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.cliente",
            ),
        ),
    ]
